# Change baseurl before deploy
baseurl = ""
languageCode = "bg-BG"
title = "BG HIP HOP ARCHIVE"
theme = "urban-archive"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "bg"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "bghiphop-archive-net"

# Enable robots.txt
enableRobotsTXT = true

# Pagination
[pagination]
pagerSize = 24

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Site parameters
[params]
  description = "Българският хип-хоп архив - колекция от български хип-хоп видеа"
  author = "BG Hip Hop Archive"

# Output formats
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

# Menu configuration
[menu]
  [[menu.main]]
    name = "Търсене"
    url = "/search/"
    weight = 30
