name: Deploy Hugo site to DO

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  push:
    branches: ["redesign", "main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.152.0'
          extended: true

      - name: Init submodules
        run: git submodule update --init --recursive 

      # Generate a custom cache key based on sync script and theme
      - name: Generate Cache Key
        id: cache_key
        run: |
            set -eo pipefail
            SCRIPT_HASH=$(
                { find scripts -type f -name "*.csx" -print0 || true; } \
                | sort -z \
                | xargs -0 -r sha256sum \
                | sha256sum \
                | cut -d ' ' -f1
            )
            THEME_HASH=$(
                { find themes -type f \( -name "*.html" -o -name "*.css" \) -print0 || true; } \
                | sort -z \
                | xargs -0 -r sha256sum \
                | sha256sum \
                | cut -d ' ' -f1
            )

            EMPTY_HASH=$(printf "" | sha256sum | cut -d ' ' -f1)
            SCRIPT_HASH=${SCRIPT_HASH:-$EMPTY_HASH}
            THEME_HASH=${THEME_HASH:-$EMPTY_HASH}
            CACHE_KEY="Linux-hugo-youtube-sync-${SCRIPT_HASH}-${THEME_HASH}"
            echo "CACHE_KEY=${CACHE_KEY}" >> "$GITHUB_ENV"


      # ✅ UPDATED: Restore cache based only on images in content/
      - name: Restore Hugo Resource Cache
        id: resources-gen-restore
        uses: actions/cache@v4
        with:
          path: resources/_gen
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-hugo-vp-images-

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dotnet-script
        run: |
          cd scripts
          dotnet tool restore
      
      - name: Run YouTube playlist sync
        shell: bash
        run: |
          echo "Starting YouTube playlist sync..."
          cd scripts
          dotnet script sync_videos.csx -- --apply
          echo "YouTube sync completed successfully"


      - name: Build
        run: hugo --minify --enableGitInfo


      # ✅ UPDATED: Save only if images changed
      - name: Save Hugo Resource Cache
        if: steps.resources-gen-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: resources/_gen
          key: ${{ env.CACHE_KEY }}

      - name: ssh deploy @ kaiyo
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 146.190.237.145
          REMOTE_USER: root
          SOURCE: public/
          TARGET: /home/projects/nginx/html/bghiphop-archive.net/
          ARGS: -avhz --delete

   